apiVersion: apps/v1
kind: Deployment
metadata:
  name: SCE-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SCE
  template:
    metadata:
      labels:
        app: SCE
    spec:
      containers:
      - name: SCE-container
        image: SCE
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: SCE-service
spec:
  selector:
    app: SCE
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort